# Generated by Django 5.0.6 on 2024-06-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_artista_alter_album_artista'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='ano_lancamento',
            field=models.SmallIntegerField(null=True),
        ),
    ]
