# Generated by Django 5.0.6 on 2024-06-27 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_alter_musica_duracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoMusica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('nota', models.SmallIntegerField()),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.musica')),
            ],
        ),
    ]
